Article.create title: 'This is an Article', snippet: 'And this here is just a summary to get you interested', content: 'This is some article content. The content is here so you as a reader can get information that a journalist has written down. An article can be about anything really and this is just an example about how it can look.', category: 'latest_news', premium: false
Article.create title: 'Flashing news from Tech world', snippet: 'It is some awesome news about e-commerce and you will never believe what happened next..', content: "We know you want to aggregate dot-com schemas. By putting collaborative methodologies in efficient e-action-items, we can recontextualize e-commerce and extend e-platforms at the same time. That is essential for wireless solutions that revolutionize proactive eyeballs. It's our viral niches that let you seize initiatives in a way that is completely disruptive.", category: 'tech', premium: true
Article.create title: 'Moto GP is replacing races with video games due to COVID-19', snippet: 'You can now see all your favourite drivers compete against eachother in video games instead of real races', content: "It's our top priority to repurpose world-class e-portals. This enables you to syndicate cutting-edge e-communities. Besides, who else can streamline plug-and-play web-readiness in a way that is as compelling? This enables you to drive e-tailers while maintaining dynamic e-niches.", category: 'sports', premium: true
Article.create title: 'Famous artist painted his whole house during quarantine', snippet: 'His wife is very upset about their now pink house', content: "As a Power-User, you want to implement bricks-and-clicks markets. I mean, when's the last time you said you could truely grow cross-platform platforms in a way that is customized? What we have then is a mission-critical system for anyone to innovate with one-to-one functionalities.", category: 'culture', premium: false
Article.create title: 'Swedens actions due to restrictions due to the Corona Virus is questioned', snippet: 'Other countries are beliving that Sweden is not doing enough to stopp the virus', content: "We know you want to sync on dynamic functionalities. We do this with magnetic solutions. What we have then is a robust system for anyone to target capital e-systems. By putting customized markets in strategic e-applications, we can facilitate deliverables and enhance infrastructures at the same time.", category: 'politics', premium: false
Article.create title: 'Attending a bootcamp can be very hard but is very fun', snippet: 'Students are saying that they are pushed to the limit but they learn a lot in a short time', content: "We offer frictionless niches. It's our holistic e-web-readiness that let you embrace platforms in a way that is completely scalable. That is essential for visionary solutions that generate distributed interfaces. By putting revolutionary e-schemas in value-added ROI, we can brand paradigms and seize e-supply-chains at the same time.", category: 'latest_news', premium: true
Article.create title: 'Oil companies are underrestimated', snippet: 'They are not that bad actually, even though they are killing baby seals', content: "It's our top priority to brand transparent e-social-media! By putting frictionless e-networks in dynamic deliverables, we can enhance e-business and deploy exchanges at the same time. Besides, who else can empower enterprise methodologies in a way that is as next-generation? We do this with intuitive e-services.", category: 'politics', premium: false
Article.create title: 'Sci-Fi is the new Rom-Com', snippet: 'Scientists say that in the future women will enjoy Sci-Fi more than Rom-Coms', content: "We know you want to target distributed functionalities! This enables you to seize frictionless e-services. Plus, you can morph next-generation content. It's our cross-platform e-exchanges that let you drive systems in a way that is completely efficient.", category: 'culture', premium: true

User.create email: 'journalist@mail.com', password: 'password', role: 'journalist'
User.create email: 'user@mail.com', password: 'password', role: 'registred_user'
